from pydantic import BaseModel
from typing import Optional

class InvoiceItem(BaseModel):
    no: int
    content: str
    quantity: str
    unit: str
    unit_price: str
    subtotal: str

class InvoiceInfo(BaseModel):
    client_name: str
    client_address: Optional[str] = ""
    client_phone: Optional[str] = ""
    project_name: str
    job_no: Optional[str] = None
    quotation_no: Optional[str] = None
    no: Optional[str] = None  # Invoice number
    date: Optional[str] = None  # Invoice issue date
    due_date: Optional[str] = None  # Payment due date
    invoice_items: list[InvoiceItem]
    total_amount: str
    currency: str
    status: Optional[str] = "pending"  # pending, paid, overdue, cancelled
    notes: Optional[str] = ""  # Additional notes

class InvoiceInfoExtractOutput(BaseModel):
    invoice_info: InvoiceInfo
    messages: list[str] = []

SYSTEM_ROLE = """
    You are an Information Extraction Agent specialized \
    in analyzing Chinese and English text \
    to extract key invoice information.
"""

TASK = """
    Step 1: Your task is to extract invoice information from the input text.

    For each invoice, extract:
    1. Customer (客戶) - Look for terms containing "有限公司", "公司", "limited", or "LLC".
    2. Project Name (項目名稱) - The project or work that was completed.
    3. Job Number (工作編號) - If provided, the original job number.
    4. Quotation Number (報價編號) - If provided, the original quotation number.
    5. Due Date (到期日) - Payment due date, if specified.
    6. Status (狀態) - Payment status (pending, paid, overdue, cancelled). Default: "pending".
    7. Line items - A list of billable items, each with a cost in MOP.
    8. Notes (備註) - Any additional notes or payment terms.
"""

PATTERN_RULES = """
  step 2: Rules for extracting invoice information:

  Pattern Recognition Rules:
  1. Customer:
    - Contains "有限公司", "公司", "limited", "LLC", or "company".
    - Usually first in the invoice.
  2. Project Description:
    - Describes the completed work/service.
    - Should match the original quotation/job if applicable.
  3. Line Items:
    - Must include price in MOP (or other currency).
    - Default unit: "Lot" if unspecified.
    - IMPORTANT: Auto-generate "no" field sequentially (1, 2, 3...) for each line item.
      Do NOT extract "no" from user input. Always start from 1.
  4. Due Date:
    - Look for terms like "到期日", "付款期限", "due date", "payment due".
    - If not specified, leave as null.
  5. Status:
    - Default to "pending" unless explicitly stated as "paid", "overdue", or "cancelled".
"""

OUTPUT_RULES = """
    step 3: Output format, MUST use **InvoiceInfoExtractOutput** schema:
    ```json
    {{
      "invoice_info": {{
        "client_name": "<client_name>",
        "client_address": "<client_address if provided, otherwise empty string>",
        "client_phone": "<client_phone if provided, otherwise empty string>",
        "project_name": "<project_name>",
        "job_no": "<job_no if provided, otherwise null>",
        "quotation_no": "<quotation_no if provided, otherwise null>",
        "no": "<invoice_no if provided, otherwise null>",
        "date": "<date if provided, otherwise null>",
        "due_date": "<due_date if provided, otherwise null>",
        "invoice_items": [
          {{
            "no": "<auto-generated: 1, 2, 3... for each line item>",
            "content": "<content>",
            "quantity": "<quantity>",
            "unit": "<unit>",
            "unit_price": "<unit_price>",
            "subtotal": "<unit_price * quantity>"
          }}
        ],
        "total_amount": "<the sum of all subtotal in invoice_items>",
        "currency": "<currency>",
        "status": "<status: pending/paid/overdue/cancelled>",
        "notes": "<notes if provided, otherwise empty string>"
      }},
      "messages": ["<your reasoning and thought process of your invoice information extraction result>"]
    }}
"""

EXAMPLES = """
    ------------------------------
    Example 1: Simple invoice with single item

    Input:
    長聯建築工程有限公司
    A3連接橋D匝道箱樑木模板支撐架計算
    工作已完成，請開具發票
    7000MOP
    付款期限：30天

    Output:
    ```json
    {{
      "invoice_info": {{
        "client_name": "長聯建築工程有限公司",
        "client_address": "",
        "client_phone": "",
        "project_name": "A3連接橋D匝道箱樑木模板支撐架計算",
        "job_no": null,
        "quotation_no": null,
        "no": null,
        "date": null,
        "due_date": "30天",
        "invoice_items": [
          {{
            "no": "1",
            "content": "A3連接橋D匝道箱樑木模板支撐架計算",
            "quantity": "1",
            "unit": "Lot",
            "unit_price": "7000",
            "subtotal": "7000"
          }}
        ],
        "total_amount": "7000",
        "currency": "MOP",
        "status": "pending",
        "notes": "工作已完成"
      }},
      "messages": ["I have extracted the invoice information from the input text. Work is completed and invoice should be issued with 30-day payment term."]
    }}

  ------------------------------
    Example 2: Invoice with multiple line items and job reference

    Input:
    金輝
    項目：A8項目模板計算
    工作編號：JCP-25-01-1
    報價編號：Q-JCP-25-01-q1

    項目明細：
    樑模板計算 5000 MOP
    牆體模板計算 5000 MOP

    備註：工作已於2025年1月15日完成，請於收到發票後14日內付款。

    Output:
    ```json
    {{
      "invoice_info": {{
        "client_name": "金輝",
        "client_address": "",
        "client_phone": "",
        "project_name": "A8項目模板計算",
        "job_no": "JCP-25-01-1",
        "quotation_no": "Q-JCP-25-01-q1",
        "no": null,
        "date": null,
        "due_date": "14日",
        "invoice_items": [
          {{
            "no": "1",
            "content": "樑模板計算",
            "quantity": "1",
            "unit": "Lot",
            "unit_price": "5000",
            "subtotal": "5000"
          }},
          {{
            "no": "2",
            "content": "牆體模板計算",
            "quantity": "1",
            "unit": "Lot",
            "unit_price": "5000",
            "subtotal": "5000"
          }}
        ],
        "total_amount": "10000",
        "currency": "MOP",
        "status": "pending",
        "notes": "工作已於2025年1月15日完成，請於收到發票後14日內付款。"
      }},
      "messages": ["I have extracted the invoice information with job reference JCP-25-01-1 and quotation reference Q-JCP-25-01-q1. The work was completed on Jan 15, 2025 with a 14-day payment term."]
    }}
"""

# Build full prompt
EXTRACT_INVOICE_PROMPT_TEMPLATE = (
    SYSTEM_ROLE +
    TASK +
    PATTERN_RULES +
    OUTPUT_RULES +
    EXAMPLES +
    "\n\nUser Input:\n{user_input}\n\nClient Info:\n{client_info}\n\nJob No:\n{job_no}\n\nQuotation No:\n{quotation_no}\n\nDate:\n{date}"
)
