from pydantic import BaseModel
from typing import Optional

class ProjectItem(BaseModel):
    no: int
    content: str
    quantity: str
    unit: str
    unit_price: str
    subtotal: str

class QuotationInfo(BaseModel):
    client_name: str
    client_address: Optional[str] = ""
    client_phone: Optional[str] = ""
    project_name: str
    no: Optional[str] = None
    date: Optional[str] = None
    project_items: list[ProjectItem]
    total_amount: str
    currency: str

class QuotationInfoExtractOutput(BaseModel):
    quotation_info: QuotationInfo
    messages: list[str] = []

SYSTEM_ROLE = """
    You are an Information Extraction Agent specialized \
    in analyzing Chinese and English text \
    to extract key quotation information.
"""

TASK = """
    Step 1: Your task is to extract quotation information from the input text.

    For each quotation, extract:
    1. Customer (客戶) - Look for terms containing "有限公司", "公司", "limited", or "LLC".
    2. Project Name (項目名稱) - The main project or work description.
       IMPORTANT: The project name and project item content should describe the WORK/SERVICE being quoted,
       NOT the client/customer name. For example, "結構安全檢測" is a project name, while "金龍建築工程有限公司" is a client name.
       - For SINGLE item quotations: project_name and content are the SAME (both describe the work).
       - For MULTIPLE item quotations: project_name is the MAIN project name, and content describes each specific line item.
    3. Line items - A list of line items, each with a cost in MOP.
"""

PATTERN_RULES = """
  step 2: Rules for identifying multiple quotations and multiple line items:
  - Data follows a repeating 3-item pattern: company - project - cost.
  - Patterns may be separated by newlines OR spaces.

  Pattern Recognition Rules:
  1. Customer:
    - Contains "有限公司", "公司", "limited", "LLC", or "company".
    - Usually first in each quotation.
  2. Project Description:
    - Between company name and cost.
    - Describes technical work/scope.
    - In MULTIPLE sets: this is the overarching project name.
  3. Line Items:
    - Each line item MUST include price in MOP.
    - Line items can be separated by:
      a) Newlines (most common): "item1 5000 MOP\nitem2 3000 MOP"
      b) Commas: "item1 5000 MOP, item2 3000 MOP"
    - Default unit: "Lot" if unspecified.
    - IMPORTANT: Auto-generate "no" field sequentially (1, 2, 3...) for each line item.
      Do NOT extract "no" from user input. Always start from 1 for each quotation.
    - When you see multiple items with prices, create SEPARATE project_items entries for each one.
"""

OUTPUT_RULES = """
    step 3: Output format, MUST use **QuotationInfoExtractOutput** schema:
    ```json
    {{
      "quotation_info": [
        {{
          "client_name": "<client_name - the customer/company name>",
          "client_address": "<client_address if provided, otherwise empty string>",
          "client_phone": "<client_phone if provided, otherwise empty string>",
          "project_name": "<project_name - the work/service description, NOT the client name>",
          "no": "<no>",
          "date": "<date>",
          "project_items": [
            {{
              "no": "<auto-generated: 1, 2, 3... for each line item>",
              "content": "<content - the specific work/service item description, NOT the client name>",
              "quantity": "<quantity>",
              "unit": "<unit>",
              "unit_price": "<unit_price>",
              "subtotal": "<unit_price * quantity>"
            }}
          ],
          "total_amount": "<the sum of all subtotal in project_items>",
          "currency": "<currency>"
        }}
      ],
      "messages": ["<your reasoning and thought process of your quotation information extraction result>"]
    }}
"""

EXAMPLES = """
    ------------------------------
    Example 1: Newline-separated and single quotation
    
    Input:
    長聯建築工程有限公司
    A3連接橋D匝道箱樑木模板支撐架計算
    7000MOP

    Output:
    ```json
    {{
      "quotation_info": [
        {{
        "client_name": "長聯建築工程有限公司",
        "client_address": "",
        "client_phone": "",
        "project_name": "A3連接橋D匝道箱樑木模板支撐架計算",
        "project_items": [
          {{
            "no": "1",
            "content": "A3連接橋D匝道箱樑木模板支撐架計算",
            "quantity": "1",
            "unit": "Lot",
            "unit_price": "7000",
            "subtotal": "7000"
          }}
          ],
        "total_amount": "7000",
        "currency": "MOP"
        }}
      ],
      "messages": ["I have extracted the quotation information from the input text."]
    }}
    
  ------------------------------
    Example 2: Single quotation with multiple line items (newline-separated)
    Input:
    金輝A8項目模板計算
    樑模板計算 5000 MOP
    牆體模板計算 5000 MOP

    Output:
    ```json
    {{
      "quotation_info": [
        {{
          "client_name": "金輝",
          "client_address": "",
          "client_phone": "",
          "project_name": "金輝A8項目模板計算",
          "project_items": [
            {{
              "no": "1",
              "content": "樑模板計算",
              "quantity": "1",
              "unit": "Lot",
              "unit_price": "5000",
              "subtotal": "5000"
            }},
            {{
              "no": "2",
              "content": "牆體模板計算",
              "quantity": "1",
              "unit": "Lot",
              "unit_price": "5000",
              "subtotal": "5000"
            }}
          ],
          "total_amount": "10000",
          "currency": "MOP"
        }}
      ],
      "messages": ["I have extracted one quotation with TWO line items (樑模板計算 and 牆體模板計算)."]
    }}

  ------------------------------
    Example 3: Multiple quotations with multiple items each
    Input:
    金輝A8項目模板計算
    樑模板計算 5000 MOP
    牆體模板計算 5000 MOP

    Citywide Development Ltd Harbor Bridge Foundation Design
    Structural Analysis & Design 120 Hours 180 MOP
    Geotechnical Investigation 45 Hours 200 MOP
    Foundation Pile Design 80 Hours 190 MOP
    Engineering Drawings Package 1 Set 8500 MOP

    Output:
    ```json
    {{
      "quotation_info": [
        {{
          "client_name": "金輝",
          "client_address": "",
          "client_phone": "",
          "project_name": "金輝A8項目模板計算",
          "project_items": [
            {{
              "no": "1",
              "content": "樑模板計算",
              "quantity": "1",
              "unit": "Lot",
              "unit_price": "5000",
              "subtotal": "5000"
            }},
            {{
              "no": "2",
              "content": "牆體模板計算",
              "quantity": "1",
              "unit": "Lot",
              "unit_price": "5000",
              "subtotal": "5000"
            }}
          ],
          "total_amount": "10000",
          "currency": "MOP"
        }},
        {{
          "client_name": "Citywide Development Ltd",
          "client_address": "",
          "client_phone": "",
          "project_name": "Harbor Bridge Foundation Design",
          "project_items": [
            {{
              "no": "1",
              "content": "Structural Analysis & Design",
              "quantity": "120",
              "unit": "Hours",
              "unit_price": "180",
              "subtotal": "21600"
            }},
            {{
              "no": "2",
              "content": "Geotechnical Investigation",
              "quantity": "45",
              "unit": "Hours",
              "unit_price": "200",
              "subtotal": "9000"
            }},
            {{
              "no": "3",
              "content": "Foundation Pile Design",
              "quantity": "80",
              "unit": "Hours",
              "unit_price": "190",
              "subtotal": "15200"
            }},
            {{
              "no": "4",
              "content": "Engineering Drawings Package",
              "quantity": "1",
              "unit": "Set",
              "unit_price": "8500",
              "subtotal": "8500"
            }}
          ],
          "total_amount": "54300",
          "currency": "HKD"
        }}
      ],
      "messages": ["I have extracted TWO separate quotations. First quotation for 金輝 has 2 items, second quotation for Citywide Development Ltd has 4 items."]
    }}
"""

  # Build full prompt
EXTRACT_QUOTATION_PROMPT_TEMPLATE= (
    SYSTEM_ROLE +
    TASK +
    PATTERN_RULES +
    OUTPUT_RULES +
    EXAMPLES +
    "\n\nUser Input:\n{user_input}\n\nClient Info:\n{client_info}\n\nQuotation No:\n{quotation_no}\n\nDate:\n{date}"
)