"""
Tool for creating new jobs in the Finance database.

Refactored to use centralized services with SQLModel ORM.

This module provides functionality to create job records with:
- Input validation and parsing
- Session-based service layer
- Error handling
- Type safety
"""

from typing import Any, Dict
from sqlmodel import Session

from app.db.engine import engine
from app.services.job_service import JobService
from app.finance_agent.utils.tool_input_parser import parse_tool_input, ToolInputError
from app.finance_agent.utils.constants import JobType


# ============================================================================
# Business Logic Functions
# ============================================================================

def _validate_and_normalize_job_data(params: Dict[str, Any]) -> tuple[int, str, str, str | None]:
    """
    Validate and normalize job creation parameters.

    Args:
        params: Raw job parameters from tool input

    Returns:
        Tuple of (company_id, job_type, title, job_no)

    Raises:
        ValueError: If validation fails
    """
    # Validate required fields
    company_id = params.get('company_id')
    if not company_id:
        raise ValueError("company_id is required")

    job_type = params.get('job_type')
    if not job_type:
        raise ValueError("job_type is required")

    job_title = params.get('job_title')
    if not job_title:
        raise ValueError("job_title is required")

    # Normalize job type to uppercase
    job_type_normalized = job_type.strip().upper()

    # Validate job type is either DESIGN or INSPECTION
    if job_type_normalized not in [JobType.DESIGN, JobType.INSPECTION]:
        raise ValueError(f"job_type must be 'DESIGN' or 'INSPECTION', got '{job_type}'")

    job_no = params.get('job_no')  # Optional

    return company_id, job_type_normalized, job_title, job_no


def _format_job_success_message(job, job_type: str) -> str:
    """
    Format success message with created job details.

    Args:
        job: Created job (DesignJob or InspectionJob ORM model)
        job_type: Job type (DESIGN or INSPECTION)

    Returns:
        Formatted success message string
    """
    return (
        f"Successfully created {job_type} job: "
        f"ID={job.id}, "
        f"Company ID={job.company_id}, "
        f"Title={job.title}, "
        f"Status={job.status}, "
        f"Job No={job.job_no}, "
        f"Created={job.date_created}, "
        f"Quotation Status={job.quotation_status}"
    )


# ============================================================================
# Main Tool Function
# ============================================================================

def create_job_tool(tool_input: Any) -> str:
    """
    Create a new job for a company using centralized JobService.

    IMPORTANT: Jobs are stored in separate tables based on type:
    - DESIGN jobs -> Finance.design_job table
    - INSPECTION jobs -> Finance.inspection_job table

    Job numbers are auto-generated by JobService with format:
    - DESIGN: JCP-{YY}-{SEQ}-{INDEX}
    - INSPECTION: JICP-{YY}-{SEQ}-{INDEX}

    Args:
        tool_input: {"company_id": int, "job_type": str, "job_title": str, "job_no": str (optional)}
            - job_type: Must be "DESIGN" or "INSPECTION"
            - job_no: Optional, will be auto-generated if not provided

    Returns:
        Success message with job details or error message

    Examples:
        >>> create_job_tool({"company_id": 5, "job_type": "DESIGN", "job_title": "空調系統設計"})
        "Successfully created DESIGN job: ID=1, Company ID=5, Title=空調系統設計, Job No=JCP-25-05-1"

        >>> create_job_tool({"company_id": 3, "job_type": "INSPECTION", "job_title": "消防安全檢查"})
        "Successfully created INSPECTION job: ID=2, Company ID=3, Title=消防安全檢查, Job No=JICP-25-04-1"
    """
    try:
        # Parse and validate input
        params = parse_tool_input(
            tool_input,
            required_keys=['company_id', 'job_type', 'job_title'],
            tool_name="create_job_tool"
        )

        # Validate and normalize job data
        try:
            company_id, job_type, job_title, job_no = _validate_and_normalize_job_data(params)
        except ValueError as e:
            return f"Error: {str(e)}"

        # Use JobService with session management
        with Session(engine) as session:
            job_service = JobService(session)

            # Create job (job_no will be auto-generated if not provided)
            if job_no:
                # If job_no provided, we need to create it differently
                # For now, let JobService generate it
                job = job_service.create_job(
                    company_id=company_id,
                    title=job_title,
                    job_type=job_type
                )
            else:
                job = job_service.create_job(
                    company_id=company_id,
                    title=job_title,
                    job_type=job_type
                )

            # Commit the transaction
            session.commit()

        # Format and return success message
        return _format_job_success_message(job, job_type)

    except ToolInputError as e:
        return f"Error: {str(e)}"
    except ValueError as e:
        return f"Validation error: {str(e)}"
    except Exception as e:
        error_msg = f"Unexpected error creating job: {str(e)}"
        print(f"[ERROR][create_job_tool] {error_msg}")
        import traceback
        traceback.print_exc()
        return error_msg
