# app/services/impl/pre_routing_logger_service_impl.py
from typing import Iterable
from uuid import UUID

from sqlmodel import Session

from app.db.supabase.engine import engine
from app.models.flow_models import FlowSchema  # ORM Schema (table model)
from app.prompt.pre_routing_logger_prompt import (
    PRE_ROUTING_LOGGER_PROMPT,
    PreRoutingLoggerOutput,
)
from app.llm.invoke_claude_llm import invoke_claude_llm
from app.dto.pre_routing_dto import (
    PreRoutingLoggerRequestDTO,
    PreRoutingLoggerResultDTO,
    PreRoutingLoggerResponseDTO,
)
from app.services import PreRoutingLoggerService


class PreRoutingLoggerServiceImpl(PreRoutingLoggerService):
    """
    Service (Pre-routing logger): encapsulates LLM summarization + DB logging.
    Controller / Node only interacts with DTOs, not directly with Session / models.
    """

    def _session_factory(self) -> Session:
        """Create a new database session."""
        return Session(engine)

    # --------------------------------------------------------------------- #
    # Public API
    # --------------------------------------------------------------------- #

    def handle(self, req: PreRoutingLoggerRequestDTO) -> PreRoutingLoggerResponseDTO:
        """
        Handle pre-routing logging:
        1) Summarize user input via LLM
        2) Log flow + summary + identified agents into DB

        NOTE:
        - Logging failure should NOT break the main flow. In case of error,
          we still return a response with the same flow_uuid.
        """
        session = self._session_factory()
        try:
            # 1) LLM summarization
            result = self._summarize_user_input(
                user_input=req.user_input,
                classifier_msg=req.classifier_msg,
            )

            # 2) DB logging
            self._log_flow_to_db(
                session=session,
                flow_uuid=req.flow_uuid,
                session_id=req.session_id,
                summary=result.summary,
                identified_agents=result.identified_agents,
            )

            return PreRoutingLoggerResponseDTO(flow_uuid=req.flow_uuid)

        except Exception as e:
            # Service-level logging; controller decides whether to swallow the error.
            print(f"[PRE_ROUTING_LOGGER SERVICE] Error: {e}")
            # Requirement: even if logging fails, the main flow should continue.
            return PreRoutingLoggerResponseDTO(flow_uuid=req.flow_uuid)

        finally:
            session.close()

    # --------------------------------------------------------------------- #
    # Private helpers
    # --------------------------------------------------------------------- #

    def _summarize_user_input(
        self,
        *,
        user_input: str,
        classifier_msg: str,
    ) -> PreRoutingLoggerResultDTO:
        """
        Call LLM to summarize the user request and identified agents.
        """
        prompt = PRE_ROUTING_LOGGER_PROMPT.format(
            user_input=user_input,
            classifier_message=classifier_msg,
        )
        print("[PRE_ROUTING_LOGGER] Invoking LLM for summarization...")
        llm_result: PreRoutingLoggerOutput = invoke_claude_llm(
            prompt,
            PreRoutingLoggerOutput,
        )

        return PreRoutingLoggerResultDTO(
            summary=llm_result.summary,
            identified_agents=list(llm_result.identified_agents or []),
        )

    def _log_flow_to_db(
        self,
        *,
        session: Session,
        flow_uuid: UUID,
        session_id: UUID,
        summary: str,
        identified_agents: Iterable[str],
    ) -> None:
        """
        Persist flow log into the DB using the FlowSchema (ORM model).

        We store:
          - flow UUID (explicitly passed from upstream, NOT auto-generated)
          - session_id
          - comma-separated identified_agents
          - user_request_summary
          - created_at (auto-generated by DB via server_default)
        """
        agents_str = ", ".join(identified_agents) if identified_agents else None

        # Use FlowSchema (ORM table model) for DB operations
        # IMPORTANT: Use flow_uuid as id to maintain trace consistency across the flow
        flow = FlowSchema(
            id=flow_uuid,  # 👈 使用上游传入的 flow_uuid，保持 trace id 一致性
            session_id=session_id,
            identified_agents=agents_str,
            user_request_summary=summary,
        )
        session.add(flow)
        session.commit()

        print(f"[PRE_ROUTING_LOGGER] ✓ Logged flow with UUID: {flow.id}")
