"""
Invoice Models for Finance.invoice, invoice_item, and payment_record tables.

Provides SQLModel ORM models for invoice management including:
- Invoice: Main invoice header
- InvoiceItem: Individual line items
- PaymentRecord: Payment tracking
"""

from sqlmodel import SQLModel, Field, Column
from typing import Optional
from datetime import date, datetime
from decimal import Decimal
from sqlalchemy import text, DECIMAL
from sqlalchemy.dialects.postgresql import TIMESTAMP
from app.models.enums import DBTable


# ========================================================================
# INVOICE MODELS
# ========================================================================

class InvoiceBase(SQLModel):
    """Shared fields for invoice create/update/read operations."""
    invoice_no: str = Field(index=True, max_length=50)
    client_id: int = Field(foreign_key="Finance.company.id")
    project_name: str = Field(max_length=200)
    date_issued: date
    due_date: date
    status: str = Field(default="DRAFT")  # DRAFT, SENT, PAID, OVERDUE, CANCELLED
    quotation_id: Optional[int] = Field(default=None, foreign_key="Finance.quotation.id")
    notes: Optional[str] = None
    currency: str = Field(default="MOP", max_length=3)


class Invoice(InvoiceBase, table=True):
    """
    Invoice model mapped to Finance.invoice table.

    Provides ORM capabilities for invoice records.

    Note: date_created is auto-generated by database server_default.
    """
    __tablename__: str = DBTable.INVOICE_TABLE.table
    __table_args__ = {"schema": DBTable.INVOICE_TABLE.schema}

    id: Optional[int] = Field(default=None, primary_key=True)

    # Database-generated field (server_default=now())
    date_created: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            TIMESTAMP(timezone=True),
            server_default=text("now()"),
            nullable=False,
        ),
    )


# ========================================================================
# INVOICE ITEM MODELS
# ========================================================================

class InvoiceItemBase(SQLModel):
    """Shared fields for invoice item operations."""
    invoice_id: int = Field(foreign_key="Finance.invoice.id")
    item_desc: str = Field(max_length=500)
    quantity: Decimal = Field(
        sa_column=Column(DECIMAL(10, 2), nullable=False)
    )
    unit_price: Decimal = Field(
        sa_column=Column(DECIMAL(10, 2), nullable=False)
    )
    amount: Decimal = Field(
        sa_column=Column(DECIMAL(10, 2), nullable=False)
    )
    unit: str = Field(default="piece", max_length=20)
    remarks: Optional[str] = None


class InvoiceItem(InvoiceItemBase, table=True):
    """
    InvoiceItem model mapped to Finance.invoice_item table.

    Represents individual line items within an invoice.
    """
    __tablename__: str = DBTable.INVOICE_ITEM_TABLE.table
    __table_args__ = {"schema": DBTable.INVOICE_ITEM_TABLE.schema}

    id: Optional[int] = Field(default=None, primary_key=True)


# ========================================================================
# PAYMENT RECORD MODELS
# ========================================================================

class PaymentRecordBase(SQLModel):
    """Shared fields for payment record operations."""
    invoice_id: int = Field(foreign_key="Finance.invoice.id")
    amount: Decimal = Field(
        sa_column=Column(DECIMAL(10, 2), nullable=False)
    )
    payment_date: date
    payment_method: str = Field(max_length=50)  # CASH, BANK_TRANSFER, CHEQUE, etc.
    reference_no: Optional[str] = Field(default=None, max_length=100)
    notes: Optional[str] = None


class PaymentRecord(PaymentRecordBase, table=True):
    """
    PaymentRecord model mapped to Finance.payment_record table.

    Tracks payments made against invoices.

    Note: date_created is auto-generated by database server_default.
    """
    __tablename__: str = DBTable.PAYMENT_RECORD_TABLE.table
    __table_args__ = {"schema": DBTable.PAYMENT_RECORD_TABLE.schema}

    id: Optional[int] = Field(default=None, primary_key=True)

    # Database-generated field (server_default=now())
    date_created: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            TIMESTAMP(timezone=True),
            server_default=text("now()"),
            nullable=False,
        ),
    )


# ========================================================================
# INPUT/OUTPUT MODELS
# ========================================================================

# Invoice Create/Update Models
class InvoiceCreate(InvoiceBase):
    """Used for invoice creation."""
    id: Optional[int] = None


class InvoiceUpdate(SQLModel):
    """Used for partial invoice updates."""
    invoice_no: Optional[str] = None
    client_id: Optional[int] = None
    project_name: Optional[str] = None
    date_issued: Optional[date] = None
    due_date: Optional[date] = None
    status: Optional[str] = None
    quotation_id: Optional[int] = None
    notes: Optional[str] = None
    currency: Optional[str] = None


class InvoiceRow(InvoiceBase):
    """Used for read operations including DB-generated fields."""
    id: int
    date_created: datetime


# Invoice Item Create/Update Models
class InvoiceItemCreate(InvoiceItemBase):
    """Used for invoice item creation."""
    id: Optional[int] = None


class InvoiceItemUpdate(SQLModel):
    """Used for partial invoice item updates."""
    invoice_id: Optional[int] = None
    item_desc: Optional[str] = None
    quantity: Optional[Decimal] = None
    unit_price: Optional[Decimal] = None
    amount: Optional[Decimal] = None
    unit: Optional[str] = None
    remarks: Optional[str] = None


class InvoiceItemRow(InvoiceItemBase):
    """Used for read operations."""
    id: int


# Payment Record Create/Update Models
class PaymentRecordCreate(PaymentRecordBase):
    """Used for payment record creation."""
    id: Optional[int] = None


class PaymentRecordUpdate(SQLModel):
    """Used for partial payment record updates."""
    invoice_id: Optional[int] = None
    amount: Optional[Decimal] = None
    payment_date: Optional[date] = None
    payment_method: Optional[str] = None
    reference_no: Optional[str] = None
    notes: Optional[str] = None


class PaymentRecordRow(PaymentRecordBase):
    """Used for read operations including DB-generated fields."""
    id: int
    date_created: datetime
