from sqlmodel import SQLModel, Field, Column
from typing import Optional
from datetime import date, datetime
from decimal import Decimal
from sqlalchemy import text, DECIMAL
from sqlalchemy.dialects.postgresql import TIMESTAMP
from app.models.enums import DBTable


# ========================================================================
# INVOICE MODELS
# ========================================================================

class InvoiceBaseModel(SQLModel):
    """Shared fields for invoice create/update/read operations."""
    invoice_no: str = Field(index=True, max_length=50)
    client_id: int = Field(foreign_key="Finance.company.id")
    project_name: str = Field(max_length=200)
    date_issued: date
    due_date: date
    status: str = Field(default="DRAFT")  # DRAFT, SENT, PAID, OVERDUE, CANCELLED
    quotation_id: Optional[int] = Field(default=None, foreign_key="Finance.quotation.id")
    notes: Optional[str] = None
    currency: str = Field(default="MOP", max_length=3)


class InvoiceSchema(InvoiceBaseModel, table=True):
    """
    ORM mapping of the Finance.invoice table Schema.
    """
    __tablename__: str = DBTable.INVOICE_TABLE.table
    __table_args__ = {"schema": DBTable.INVOICE_TABLE.schema}

    id: Optional[int] = Field(default=None, primary_key=True)

    # DB generated timestamp, application does not pass, filled by server_default(now())
    date_created: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            TIMESTAMP(timezone=True),
            server_default=text("now()"),
            nullable=False,
        ),
    )

# ============================================================
# Base: Shared fields (NOT a table)
# ============================================================

class InvoiceItemBaseModel(SQLModel):
    """Shared fields for invoice item operations."""
    invoice_id: int = Field(foreign_key="Finance.invoice.id")
    item_desc: str = Field(max_length=500)
    quantity: Decimal = Field(
        sa_column=Column(DECIMAL(10, 2), nullable=False)
    )
    unit_price: Decimal = Field(
        sa_column=Column(DECIMAL(10, 2), nullable=False)
    )
    amount: Decimal = Field(
        sa_column=Column(DECIMAL(10, 2), nullable=False)
    )
    unit: str = Field(default="piece", max_length=20)
    remarks: Optional[str] = None


class InvoiceItemSchema(InvoiceItemBaseModel, table=True):
    """
    ORM mapping of the Finance.invoice_item table Schema.

    Note:
    - amount is generated by DB (GENERATED ALWAYS AS quantity * unit_price).
    """
    __tablename__: str = DBTable.INVOICE_ITEM_TABLE.table
    __table_args__ = {"schema": DBTable.INVOICE_ITEM_TABLE.schema}

    id: Optional[int] = Field(default=None, primary_key=True)


# ============================================================
# Base: Shared fields (NOT a table)
# ============================================================

class PaymentRecordBaseModel(SQLModel):
    """Shared fields for payment record operations."""
    invoice_id: int = Field(foreign_key="Finance.invoice.id")
    amount: Decimal = Field(
        sa_column=Column(DECIMAL(10, 2), nullable=False)
    )
    payment_date: date
    payment_method: str = Field(max_length=50)  # CASH, BANK_TRANSFER, CHEQUE, etc.
    reference_no: Optional[str] = Field(default=None, max_length=100)
    notes: Optional[str] = None


class PaymentRecordSchema(PaymentRecordBaseModel, table=True):
    """
    ORM mapping of the Finance.payment_record table Schema.

    Note:
    - date_created is generated by DB, application does not pass, filled by server_default(now()).
    """
    __tablename__: str = DBTable.PAYMENT_RECORD_TABLE.table
    __table_args__ = {"schema": DBTable.PAYMENT_RECORD_TABLE.schema}

    id: Optional[int] = Field(default=None, primary_key=True)

    # DB generated timestamp, application does not pass, filled by server_default(now())
    date_created: Optional[datetime] = Field(
        default=None,
        sa_column=Column(
            TIMESTAMP(timezone=True),
            server_default=text("now()"),
            nullable=False,
        ),
    )

# ============================================================
# Model: Business data shape / DTO
# ============================================================

class InvoiceCreateModel(SQLModel):
    """Used for invoice creation."""
    id: Optional[int] = None


class InvoiceUpdateModel(SQLModel):
    """Used for partial invoice updates."""
    invoice_no: Optional[str] = None
    client_id: Optional[int] = None
    project_name: Optional[str] = None
    date_issued: Optional[date] = None
    due_date: Optional[date] = None
    status: Optional[str] = None
    quotation_id: Optional[int] = None
    notes: Optional[str] = None
    currency: Optional[str] = None


class InvoiceReadModel(SQLModel):
    """Used for read operations including DB-generated fields."""
    id: int
    date_created: datetime


class InvoiceItemCreateModel(SQLModel):
    """Used for invoice item creation."""
    id: Optional[int] = None


class InvoiceItemUpdateModel(SQLModel):
    """Used for partial invoice item updates."""
    invoice_id: Optional[int] = None
    item_desc: Optional[str] = None
    quantity: Optional[Decimal] = None
    unit_price: Optional[Decimal] = None
    amount: Optional[Decimal] = None
    unit: Optional[str] = None
    remarks: Optional[str] = None


class InvoiceItemReadModel(SQLModel):
    """Used for read operations."""
    id: int


class PaymentRecordCreateModel(SQLModel):
    """Used for payment record creation."""
    id: Optional[int] = None


class PaymentRecordUpdateModel(SQLModel):
    """Used for partial payment record updates."""
    invoice_id: Optional[int] = None
    amount: Optional[Decimal] = None
    payment_date: Optional[date] = None
    payment_method: Optional[str] = None
    reference_no: Optional[str] = None
    notes: Optional[str] = None


class PaymentRecordReadModel(SQLModel):
    """Used for read operations including DB-generated fields."""
    id: int
    date_created: datetime
